Repository FDio/govpp, pull requests merged in 2023-05, with the labels that each got.

#127 Invalidate msgTable map during reconnect
  adapter/socketclient/socketclient.go
Labels: bug

#128 Add README for examples
  README.md
  examples/README.md
Labels: docs

#126 Fix race in statsclient during reconnect
  adapter/statsclient/statsclient.go
Labels: bug

#134 Update Dockerfile.integration
  test/build/Dockerfile.integration
Labels: bug, ci
