Repository FDio/govpp, pull requests merged in 2023-06, with the labels that each got.

#131 Fix channel pool
  core/channel.go
  core/connection.go
  core/log.go
  examples/perf-bench/perf-bench.go
Labels: bug, wip

#130 Refactor resolving VPP API input
  .gitignore
  Makefile
  binapi/adl/adl.ba.go
  binapi/cnat/cnat.ba.go
  binapi/crypto_sw_scheduler/crypto_sw_scheduler.ba.go
  binapi/flow/flow.ba.go
  binapi/mdata/mdata.ba.go
  binapi/oddbuf/oddbuf.ba.go
  binapi/pnat/pnat.ba.go
  binapi/tracedump/tracedump.ba.go
  binapi/wireguard/wireguard.ba.go
  binapigen/binapigen.go
  binapigen/generate_api.go
  binapigen/vppapi.go
  binapigen/vppapi/input.go
  binapigen/vppapi/input_test.go
  binapigen/vppapi/parse_json.go
  binapigen/vppapi/source.go
  binapigen/vppapi/source_test.go
  binapigen/vppapi/util.go
  binapigen/vppapi/vppapi.go
  cmd/govpp/cmd.go
  cmd/govpp/cmd_cli.go
  cmd/govpp/cmd_diff.go
  cmd/govpp/cmd_export.go
  cmd/govpp/cmd_generate.go
  cmd/govpp/cmd_http.go
  cmd/govpp/cmd_lint.go
  cmd/govpp/cmd_vppapi.go
  cmd/govpp/cmd_vppapi_diff.go
  cmd/govpp/cmd_vppapi_export.go
  cmd/govpp/cmd_vppapi_lint.go
  cmd/govpp/cmd_vppapi_ls.go
  cmd/govpp/compare.go
  cmd/govpp/formatter.go
  cmd/govpp/input.go
  cmd/govpp/linter.go
  cmd/govpp/log.go
  cmd/govpp/options.go
  docs/GOVPP_CLI.md
Labels: enhancement

#121 binapigen: initial support for counters and paths
  binapigen/vppapi/api_schema.go
  binapigen/vppapi/parse_json.go
Labels: enhancement, vppapi

#137 Skip running CI tests for docs updates
  .github/workflows/test.yaml
Labels: ci

#138 Fix memory leak for timers
  adapter/socketclient/socketclient.go
Labels: bug

#135 Improvements for GoVPP CLI
  binapigen/generator.go
  binapigen/vppapi.go
  binapigen/vppapi/input.go
  binapigen/vppapi/input_test.go
  binapigen/vppapi/source.go
  binapigen/vppapi/util.go
  cmd/govpp/cli.go
  cmd/govpp/cmd.go
  cmd/govpp/cmd_cli.go
  cmd/govpp/cmd_generate.go
  cmd/govpp/cmd_http.go
  cmd/govpp/cmd_vppapi.go
  cmd/govpp/cmd_vppapi_diff.go
  cmd/govpp/cmd_vppapi_export.go
  cmd/govpp/cmd_vppapi_lint.go
  cmd/govpp/cmd_vppapi_ls.go
  cmd/govpp/compare.go
  cmd/govpp/formatter.go
  cmd/govpp/input.go
  cmd/govpp/linter.go
  cmd/govpp/options.go
  cmd/govpp/util.go
  go.mod
  go.sum
Labels: enhancement

#136 Add VPP 23.06 to CI
  .github/workflows/test.yaml
Labels: ci
