Repository FDio/govpp, pull requests merged in 2024-06, with the labels that each got.

#221 fix wasted control_ping_id caching
  core/connection.go
Labels: bug

#222 Update Go
  .github/workflows/test.yaml
  Dockerfile
  test/build/Dockerfile.integration
Labels: dependencies

#223 Minor changes
  adapter/socketclient/socketclient.go
  binapigen/vppapi/input.go
  cmd/govpp/cmd_vppapi_diff.go
  cmd/govpp/compare.go
  cmd/govpp/input.go
  cmd/govpp/util.go
  codec/buffer.go
  codec/codec.go
  codec/codec_test.go
  codec/msg_codec.go
  docs/GOVPP_CLI.md
  test/integration/README.md
  test/integration/main_test.go
  test/integration/trace_test.go
  test/vpptesting/vpplauncher/vpplauncher.go
  test/vpptesting/vpptest.go
Labels: enhancement
